package info.cangshudoudou.msgbox.utils;

public class ErrorCodeConstants {
    public static final String ERR_CATEGORY_NAME_REQUIRED = "ERR_CATEGORY_NAME_REQUIRED";
    public static final String ERR_CATEGORY_NAME_TOO_LONG = "ERR_CATEGORY_NAME_TOO_LONG";
    public static final String ERR_CATEGORY_DESCRIPTION_TOO_LONG = "ERR_CATEGORY_DESCRIPTION_TOO_LONG";
    public static final String ERR_CATEGORY_NAME_DUPLICATED = "ERR_CATEGORY_NAME_DUPLICATED";
    public static final String ERR_CATEGORY_PARENT_NOT_EXISTED = "ERR_CATEGORY_PARENT_NOT_EXISTED";
    public static final String ERR_CATEGORY_NOT_EXISTED = "ERR_CATEGORY_NOT_EXISTED";
    public static final String ERR_CATEGORY_DELETE_HAS_CHILDREN = "ERR_CATEGORY_DELETE_HAS_CHILDREN";
    public static final String ERR_CATEGORY_PARENT_EQUALS_SELF = "ERR_CATEGORY_PARENT_EQUALS_SELF";
    public static final String ERR_CATEGORY_HIERARCHY_INVALID = "ERR_CATEGORY_HIERARCHY_INVALID";
    
    public static final String ERR_MESSAGE_CONTENT_REQUIRED = "ERR_MESSAGE_CONTENT_REQUIRED";
    public static final String ERR_MESSAGE_CATEGORY_REQUIRED = "ERR_MESSAGE_CATEGORY_REQUIRED";
    public static final String ERR_MESSAGE_RANK_OUT_OF_RANGE = "ERR_MESSAGE_RANK_OUT_OF_RANGE";
    public static final String ERR_MESSAGE_SOURCE_TOO_LONG = "ERR_MESSAGE_SOURCE_TOO_LONG";
    public static final String ERR_MESSAGE_NOT_EXISTED = "ERR_MESSAGE_NOT_EXISTED";
    public static final String ERR_MESSAGE_ALREADY_DISABLED = "ERR_MESSAGE_ALREADY_DISABLED";
    public static final String ERR_MESSAGE_ALREADY_ENABLED = "ERR_MESSAGE_ALREADY_ENABLED";
}
